[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/profiles.html
profile = "black"
multi_line_output = 3
skip = "env"
src_paths = ["event_creation_onboarding/src/"]

[tool.mypy]
exclude = [
    "tests",
    "env",
    "venv"
]
python_version = 3.8
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

# .coveragerc to control coverage.py
[tool.coverage.run]
branch = true
source = ["event_creation_onboarding/src/app/"]
[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't complain if tests don't hit defensive assertion code:
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod"
]
omit = ["event_creation_onboarding/src/tests/*"]
ignore_errors = true
